name: CI-patched2

on:
  workflow_dispatch: # allows manual triggering

env:
  GGML_NLOOP: 3
  GGML_N_THREADS: 1
  LLAMA_LOG_COLORS: 1
  LLAMA_LOG_PREFIX: 1
  LLAMA_LOG_TIMESTAMPS: 1

jobs:
  ubuntu-cpu:
    strategy:
      matrix:
        include:
          - build: 'arm64'
            os: ubuntu-24.04-arm

    runs-on: ${{ matrix.os }}

    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v6

      - name: ccache
        if: ${{ matrix.build != 's390x' && matrix.build != 'ppc64le' }}
        uses: ggml-org/ccache-action@v1.2.21
        with:
          key: ubuntu-cpu-${{ matrix.build }}
          evict-old-files: 1d
          save: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}

      - name: Toolchain workaround (GCC 14)
        if: ${{ contains(matrix.os, 'ubuntu-24.04-arm') }}
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-14-x86-64-linux-gnu g++-14-x86-64-linux-gnu patchelf
          echo "CC=x86_64-linux-gnu-gcc-14" >> "$GITHUB_ENV"
          echo "CXX=x86_64-linux-gnu-g++-14" >> "$GITHUB_ENV"
      - name: Swap Endianness
        id: endianness
        if: ${{ matrix.build == 's390x' }}
        run: |
          for f in models/*.gguf; do
            echo YES | python3 gguf-py/gguf/scripts/gguf_convert_endian.py $f big
          done
      - name: Build
        id: cmake_build
        run: |
          x86_64-linux-gnu-gcc-14 --version
          x86_64-linux-gnu-g++-14 --version
          cmake -B build \
            -DLLAMA_FATAL_WARNINGS=ON \
            -DGGML_BACKEND_DL=ON \
            -DGGML_NATIVE=OFF \
            -DGGML_CPU_ALL_VARIANTS=ON \
            -DLLAMA_BUILD_WEBUI=ON
          cat build/CMakeFiles/*/CMakeSystem.cmake
          sed -i '335s/${VERSION}/b9855/' scripts/ui-assets.cmake
          sed -i 's/aarch64/x86_64/' build/CMakeFiles/*/CMakeSystem.cmake
          echo after
          cat build/CMakeFiles/*/CMakeSystem.cmake
          time cmake --build build --config Release -j $(nproc)
          mkdir build2/
          mv build/bin/ build2/llama-b9855a/
          for f in build2/llama-b9855a/llama-*; do
            patchelf --set-rpath '$ORIGIN' $f
            patchelf --add-needed 'libggml.so.0' $f
          done
      - name: Upload Build Artifact
        if: ${{ always() && steps.cmake_build.outcome == 'success' }}
        uses: actions/upload-artifact@v6
        with:
          name: llama-b9855a-bin-ubuntu-x64
          path: build2/
