name: CI (cpu)

on:
  workflow_dispatch: # allows manual triggering
  push:
    branches:
      - master
    paths: [
      '.github/workflows/build-cpu.yml',
      '.github/workflows/build-cmake-pkg.yml',
      '**/CMakeLists.txt',
      '**/.cmake',
      '**/*.h',
      '**/*.hpp',
      '**/*.c',
      '**/*.cpp',
    ]

  pull_request:
    types: [opened, synchronize, reopened]
    paths: [
      '.github/workflows/build-cpu.yml',
      '.github/workflows/build-cmake-pkg.yml',
      '**/CMakeLists.txt',
      '**/.cmake',
      '**/*.h',
      '**/*.hpp',
      '**/*.c',
      '**/*.cpp'
    ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

env:
  GGML_NLOOP: 3
  GGML_N_THREADS: 1
  LLAMA_ARG_LOG_COLORS: 1
  LLAMA_ARG_LOG_PREFIX: 1
  LLAMA_ARG_LOG_TIMESTAMPS: 1

jobs:
  build-cmake-pkg:
    uses: ./.github/workflows/build-cmake-pkg.yml

  ubuntu:
    strategy:
      matrix:
        include:
          - build: 'x64'
            os: ubuntu-24.04

    runs-on: ${{ matrix.os }}

    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v6

      - name: ccache
        uses: ggml-org/ccache-action@v1.2.21
        with:
          key: cpu-${{ matrix.os }}
          evict-old-files: 1d
          save: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}

      - name: Toolchain workaround (GCC 14)
        if: ${{ contains(matrix.os, 'ubuntu-24.04') }}
        run: |
          sudo apt-get install -y gcc-14 g++-14
          echo "CC=gcc-14" >> "$GITHUB_ENV"
          echo "CXX=g++-14" >> "$GITHUB_ENV"

      - name: Build
        id: cmake_build
        run: |
          cmake -B build \
            -DLLAMA_FATAL_WARNINGS=ON \
            -DGGML_RPC=OFF \
            -DGGML_NATIVE=OFF \
            -DGGML_CPU_ALL_VARIANTS=ON
          sed -i '335s/${VERSION}/b9767/' scripts/ui-assets.cmake
          cmake --build build --config Release -j $(nproc)
          mkdir build2/
          mv build/bin/ build2/llama-b9767/
          for f in build2/llama-b9767/llama-*; do
            patchelf --set-rpath '$ORIGIN' $f
            patchelf --add-needed 'libggml.so.0' $f
          done
      - name: Upload Build Artifact
        if: ${{ always() && steps.cmake_build.outcome == 'success' }}
        uses: actions/upload-artifact@v6
        with:
          name: llama-b9767-bin-ubuntu-x64
          path: build2/
